### ISSUE TITLE
Won't follow file links

### ISSUE THREAD

**Issue by jamaica474** [codetheweb/serverless-step-functions-local#5]
My step functions definitions became rather large and I had to split each to several files. That's when I saw this error: 

When I try to start step functions offline I see this error:
`"MissingRequiredParameter: Missing required key 'definition' in params" (serverless-step-functions-local/index.js:81)`

#### Relevant part of config
```stepFunctions:
  validate: false
  stateMachines:
    postingPreparation: ${file(serverless-yml-components/step-functions.yml):PREPARE_POSTING }
    deliverBatch: ${file(serverless-yml-components/step-functions.yml):DELIVER_BATCH }
```

#### Error
``` MissingRequiredParameter: Missing required key 'definition' in params
      at ParamValidator.fail (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/param_validator.js:50:37)
      at ParamValidator.validateStructure (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/param_validator.js:61:14)
      at ParamValidator.validateMember (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/param_validator.js:88:21)
      at ParamValidator.validate (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/param_validator.js:34:10)
      at Request.VALIDATE_PARAMETERS (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/event_listeners.js:126:42)
      at Request.callListeners (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at callNextListener (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at /home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/event_listeners.js:86:9
      at finish (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/config.js:362:7)
      at /home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/config.js:380:9
      at EnvironmentCredentials.get (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/credentials.js:127:7)
      at getAsyncCredentials (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/config.js:374:24)
      at Config.getCredentials (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/config.js:394:9)
      at Request.VALIDATE_CREDENTIALS (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/event_listeners.js:81:26)
      at Request.callListeners (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
      at Request.emit (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at Request.runTo (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/request.js:403:15)
      at /home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/request.js:792:12
      at new Promise (<anonymous>)
      at Request.promise (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/node_modules/aws-sdk/lib/request.js:778:12)
      at Promise.all.Object.keys.map.stateMachineName (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/index.js:111:8)
      at Array.map (<anonymous>)
      at ServerlessStepFunctionsLocal.createEndpoints (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/index.js:107:73)
      at Object.offline:start:init [as hook] (/home/arthem/projects/posting-delivery-pipeline/distribution/node_modules/serverless-step-functions-local/index.js:42:20)
 ```

**Comment by adambartholomew** [comment]
I've noticed this as well. Unfortunately, the plugin does not parse any form of variable within the serverless yml file, it simply uses the raw parsed file.
